spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/postgres
    username: testuser
    password: password
    platform: POSTGRESQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

shayShayApi: https://shayshay.p.rapidapi.com

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: HEADERS